"""
Tutorial: F_IS vs BOO on TorchDisorder SiO2 Glass, then MACE MD
================================================================

What this tutorial covers
--------------------------
1. Load a TorchDisorder-generated SiO2 glass and a crystalline reference.
2. Compute F_IS (local inversion symmetry) alongside BOO (q4, q6) on both.
3. Discuss what each metric captures and why F_IS is complementary to BOO.
4. Use the MACE-MP-0 universal potential via torch_sim to relax the glass,
   compute energies, and run a short NVT molecular-dynamics trajectory.
5. Track F_IS along the MD trajectory to observe structural relaxation.

Background
----------
Bond-orientational order (BOO: q4, q6, Steinhardt 1983) measures how
tetrahedral or ordered the coordination shell is around each atom.  It is
widely used but does NOT capture whether the environment is centrosymmetric.

F_IS (Milkus & Zaccone, PRB 2016; JCTC 2026 generalization) measures the
fraction of local inversion symmetry:

    Xi_i  = Σ_j  R_ij · n̂_ij^μ · n̂_ij^ν · n̂_ij        (3-vector)
    D_i   = Σ_j (R_ij · n̂_ij^μ · n̂_ij^ν)²
    F_IS_i = 1 − |Xi_i|² / D_i   (averaged over shear planes xy, xz, yz)

Key values:
  - Two antiparallel bonds of equal length → F_IS = 1  (perfect inversion)
  - Single bond                            → F_IS = 0  (no inversion)
  - Perfect SiO4 tetrahedron (Td)         → F_IS = −1/3 (Td has no inversion)

F_IS correlates more strongly with vibrational and elastic properties of
glasses than BOO.  A TorchDisorder-optimized glass (which satisfies both
scattering data AND structural constraints) should exhibit a F_IS distribution
that is physically more realistic than a naively rattled crystal.

References
----------
Milkus & Zaccone, PRB 93, 094204 (2016)
Local symmetry predictors of mechanical stability in glasses, Sci. Adv. (2022)
Theory of Disordered Solids (Zaccone), Springer (2023)
"""

# ============================================================================
# Imports
# ============================================================================

import math
from pathlib import Path
import numpy as np
import torch
import torch_sim as ts
from torch_sim.io import atoms_to_state, state_to_atoms

from pymatgen.core import Structure
from ase import Atoms

from torchdisorder.engine.order_params import TorchSimOrderParameters

# Optional imports — warn gracefully if not available
try:
    from mace.calculators.foundations_models import mace_mp
    MACE_AVAILABLE = True
except Exception:
    MACE_AVAILABLE = False
    print("MACE not available — MD section will be skipped.")

# ============================================================================
# Paths
# ============================================================================

REPO_ROOT = Path(__file__).parent.parent
DATA = REPO_ROOT / "data" / "crystal-structures"

# The crystalline reference structure (always available in the repo)
CRYSTAL_CIF = DATA / "c-SiO2.cif"

# The TorchDisorder-optimized glass (generated by running train.py).
# If it is not present yet, the tutorial falls back to the crystal for
# demonstration purposes.
GLASS_CIF = DATA / "sio2_glass.cif"

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {DEVICE}")

SI_Z = 14
O_Z  = 8


# ============================================================================
# Helper: pymatgen Structure → torch_sim SimState
# ============================================================================

def structure_to_state(struct: Structure, device: str = "cpu") -> ts.SimState:
    """Convert a pymatgen Structure to a torch_sim SimState."""
    positions  = torch.tensor(struct.cart_coords, dtype=torch.float32, device=device)
    cell       = torch.tensor(struct.lattice.matrix, dtype=torch.float32, device=device)
    atomic_numbers = torch.tensor(
        [site.specie.Z for site in struct], dtype=torch.long, device=device
    )
    return ts.SimState(
        positions=positions,
        cell=cell.unsqueeze(0),
        atomic_numbers=atomic_numbers,
        pbc=torch.tensor([True, True, True]),
        masses=atomic_numbers.float(),
    )


# ============================================================================
# Step 1 — Load structures
# ============================================================================

print("\n" + "=" * 60)
print("Step 1 — Load SiO2 structures")
print("=" * 60)

crystal = Structure.from_file(str(CRYSTAL_CIF))
print(f"Crystal:   {len(crystal)} atoms, cell ≈ {crystal.lattice.a:.2f} Å")

if GLASS_CIF.exists():
    glass = Structure.from_file(str(GLASS_CIF))
    print(f"Glass:     {len(glass)} atoms (TorchDisorder-optimized)")
    has_glass = True
else:
    print("Glass CIF not found — run `bash scripts/run_sio2.sh` to generate it.")
    print("Using a rattled crystal as a stand-in for demonstration.")
    import copy
    glass = copy.deepcopy(crystal)
    # Rattle each site by a random displacement (σ = 0.15 Å) to mimic disorder
    rng = np.random.default_rng(42)
    for site in glass:
        site.coords[:] += rng.normal(0, 0.15, 3)
    has_glass = False

state_crystal = structure_to_state(crystal, device=DEVICE)
state_glass   = structure_to_state(glass,   device=DEVICE)


# ============================================================================
# Step 2 — Build the order-parameter calculator
# ============================================================================

print("\n" + "=" * 60)
print("Step 2 — Set up order-parameter calculator")
print("=" * 60)

#  cutoff = 2.2 Å captures the first Si–O coordination shell in SiO2
op_calc = TorchSimOrderParameters(
    cutoff=2.2,
    device=DEVICE,
    max_neighbors=8,
    fis_mode="variable_R",    # recommended JCTC 2026 generalization
)

# Atom indices for Si (central atoms) and O (neighbor filter)
si_idx_crystal = torch.where(state_crystal.atomic_numbers == SI_Z)[0]
si_idx_glass   = torch.where(state_glass.atomic_numbers   == SI_Z)[0]

print(f"Si atoms in crystal : {len(si_idx_crystal)}")
print(f"Si atoms in glass   : {len(si_idx_glass)}")


# ============================================================================
# Step 3 — Compute F_IS and BOO (q4, q6) on both structures
# ============================================================================

print("\n" + "=" * 60)
print("Step 3 — Compute F_IS and BOO")
print("=" * 60)

# We compute four order parameters simultaneously for each Si atom.
# element_filter=[O_Z] restricts neighbors to oxygen only.
ops_crystal = op_calc(
    state_crystal, si_idx_crystal,
    order_params=["fis", "q4", "q6", "tet"],
    element_filter=[O_Z],
)
ops_glass = op_calc(
    state_glass, si_idx_glass,
    order_params=["fis", "q4", "q6", "tet"],
    element_filter=[O_Z],
)

print("\nCrystalline c-SiO2:")
for key, vals in ops_crystal.items():
    print(f"  {key:4s}  mean={vals.mean().item():+.4f}  std={vals.std().item():.4f}")

print("\nSiO2 glass (TorchDisorder or rattled crystal):")
for key, vals in ops_glass.items():
    print(f"  {key:4s}  mean={vals.mean().item():+.4f}  std={vals.std().item():.4f}")


# ============================================================================
# Step 4 — Compare F_IS vs BOO: what each captures
# ============================================================================

print("\n" + "=" * 60)
print("Step 4 — Compare F_IS vs BOO")
print("=" * 60)

fis_c = ops_crystal["fis"].cpu()
q4_c  = ops_crystal["q4"].cpu()
fis_g = ops_glass["fis"].cpu()
q4_g  = ops_glass["q4"].cpu()

print("""
Interpretation guide
--------------------
q4 (Steinhardt):
  Measures tetrahedral ORDER of the coordination shell.
  q4 ≈ 0.51 for a perfect tetrahedron.
  High q4 → well-ordered tetrahedral environment.
  A distorted tetrahedron can still have moderate q4.

F_IS (Milkus & Zaccone):
  Measures INVERSION SYMMETRY of the coordination shell.
  F_IS = 1   → centrosymmetric environment (e.g. antiparallel bond pairs).
  F_IS = −1/3 → perfect Td tetrahedron (Td has NO inversion centre).
  F_IS correlates with local elastic stiffness and vibrational properties.
  A structure with the same q4 but higher F_IS will generally be stiffer.

Key insight:
  Two Si atoms can have identical q4 but different F_IS if their bond-length
  distributions differ in symmetry.  F_IS is sensitive to asymmetric distortions
  that BOO misses.  The TorchDisorder-optimized glass (constrained to match
  experimental scattering AND structural order parameters) should therefore
  produce a F_IS distribution that is physically more meaningful than
  a structure that only matches scattering data.
""")

fis_delta = fis_g.mean() - fis_c.mean()
q4_delta  = q4_g.mean()  - q4_c.mean()
print(f"Δ F_IS (glass − crystal) = {fis_delta:+.4f}")
print(f"Δ q4   (glass − crystal) = {q4_delta:+.4f}")
print()
print("A positive ΔF_IS means the glass has a more centrosymmetric local")
print("environment on average — which would indicate higher mechanical stability.")


# ============================================================================
# Step 5 — MACE potential: energy and forces on the glass
# ============================================================================

print("\n" + "=" * 60)
print("Step 5 — MACE potential (energy + forces)")
print("=" * 60)

if not MACE_AVAILABLE:
    print("Skipping — install mace-torch to enable this section.")
else:
    # Load the MACE-MP-0 universal potential (downloads weights on first run)
    print("Loading MACE-MP-0 (small)…")
    calc_mace = mace_mp(model="small", device=DEVICE, default_dtype="float32")

    # Convert glass pymatgen Structure → ASE Atoms for MACE
    ase_glass = glass.to_ase_atoms()
    ase_glass.calc = calc_mace

    energy = ase_glass.get_potential_energy()
    forces = ase_glass.get_forces()

    print(f"Total energy        : {energy:.3f} eV")
    print(f"Energy per atom     : {energy / len(ase_glass):.4f} eV/atom")
    print(f"Max force component : {np.abs(forces).max():.4f} eV/Å")
    print(f"RMS force           : {np.sqrt((forces**2).mean()):.4f} eV/Å")


# ============================================================================
# Step 6 — FIRE relaxation with MACE via torch_sim
# ============================================================================

print("\n" + "=" * 60)
print("Step 6 — FIRE relaxation with torch_sim + MACE")
print("=" * 60)

if not MACE_AVAILABLE:
    print("Skipping — MACE not available.")
else:
    from torch_sim.io import atoms_to_state

    # Convert ASE → torch_sim SimState
    state_for_relax = atoms_to_state(ase_glass, device=DEVICE)

    # Build a torch_sim-compatible MACE model
    # (torch_sim wraps MACE as a StatefulModel for integration with its loop)
    try:
        from torch_sim.models.mace import MaceModel
        mace_model = MaceModel(
            model=calc_mace.models[0],
            device=DEVICE,
            dtype=torch.float32,
            compute_forces=True,
            compute_stress=False,
        )

        # FIRE minimization (fast inertial relaxation engine)
        from torch_sim.optimizers import unit_cell_fire

        fire_state, trajectory = unit_cell_fire(
            system=state_for_relax,
            model=mace_model,
            dt_max=0.5,           # fs
            n_max=200,            # max iterations
            force_tol=0.05,       # eV/Å
        )

        ase_relaxed   = state_to_atoms(fire_state)[0]
        energy_relax  = ase_relaxed.get_potential_energy()
        print(f"Energy after FIRE   : {energy_relax:.3f} eV ({energy_relax/len(ase_relaxed):.4f} eV/atom)")
        print(f"Energy gained       : {energy_relax - energy:.3f} eV")

        # Compute F_IS on the relaxed structure and compare
        state_relaxed_ts = atoms_to_state(ase_relaxed, device=DEVICE)
        si_idx_relaxed   = torch.where(state_relaxed_ts.atomic_numbers == SI_Z)[0]
        ops_relaxed = op_calc(
            state_relaxed_ts, si_idx_relaxed,
            order_params=["fis", "q4", "tet"],
            element_filter=[O_Z],
        )
        print("\nAfter FIRE relaxation:")
        for key, vals in ops_relaxed.items():
            print(f"  {key:4s}  mean={vals.mean().item():+.4f}  std={vals.std().item():.4f}")

    except ImportError:
        print("torch_sim.models.mace or torch_sim.optimizers not found in this version.")
        print("Check your torch_sim version — API may differ.")


# ============================================================================
# Step 7 — NVT Molecular Dynamics with torch_sim + MACE
# ============================================================================

print("\n" + "=" * 60)
print("Step 7 — NVT MD with torch_sim + MACE")
print("=" * 60)

if not MACE_AVAILABLE:
    print("Skipping — MACE not available.")
else:
    try:
        from torch_sim.integrators import nvt_langevin

        T_K          = 300.0        # Kelvin
        dt_fs        = 1.0          # femtoseconds
        n_steps      = 500          # total MD steps
        log_every    = 100          # compute F_IS every N steps

        print(f"Running NVT Langevin MD at {T_K} K for {n_steps} steps (dt = {dt_fs} fs)…")

        # Re-use the relaxed state as starting point (or fall back to glass)
        try:
            md_start = fire_state
        except NameError:
            md_start = atoms_to_state(ase_glass, device=DEVICE)

        # torch_sim integrator returns a generator / iterable over states
        integrator = nvt_langevin(
            system=md_start,
            model=mace_model,
            dt=dt_fs * 1e-3,        # ts uses ps internally: 1 fs = 0.001 ps
            temperature=T_K,
            friction=0.01,          # ps⁻¹ — Langevin damping coefficient
        )

        fis_trajectory = []
        q4_trajectory  = []
        tet_trajectory = []
        step_labels    = []

        for step, state_md in enumerate(integrator):
            if step >= n_steps:
                break

            if step % log_every == 0:
                si_md = torch.where(state_md.atomic_numbers == SI_Z)[0]
                ops_md = op_calc(
                    state_md, si_md,
                    order_params=["fis", "q4", "tet"],
                    element_filter=[O_Z],
                )
                fis_val = ops_md["fis"].mean().item()
                q4_val  = ops_md["q4"].mean().item()
                tet_val = ops_md["tet"].mean().item()
                fis_trajectory.append(fis_val)
                q4_trajectory.append(q4_val)
                tet_trajectory.append(tet_val)
                step_labels.append(step)
                print(f"  step {step:4d}  F_IS={fis_val:+.4f}  q4={q4_val:.4f}  tet={tet_val:.4f}")

        print("\nMD trajectory summary")
        print(f"  F_IS:  {np.mean(fis_trajectory):+.4f} ± {np.std(fis_trajectory):.4f}")
        print(f"  q4:    {np.mean(q4_trajectory):.4f} ± {np.std(q4_trajectory):.4f}")
        print(f"  tet:   {np.mean(tet_trajectory):.4f} ± {np.std(tet_trajectory):.4f}")

    except (ImportError, AttributeError) as exc:
        print(f"NVT integrator not available in this torch_sim version: {exc}")
        print("Try: ts.integrate.nvt_langevin or check torch_sim docs for your version.")


# ============================================================================
# Step 8 — Summary: F_IS vs BOO
# ============================================================================

print("\n" + "=" * 60)
print("Step 8 — Summary")
print("=" * 60)

print(f"""
Key takeaways
-------------
1. q4/q6 (BOO) measure how ORDERED the tetrahedral shell is.
   They are blind to inversion asymmetry within a given order level.

2. F_IS measures CENTROSYMMETRY of the local elastic environment.
   It correlates directly with the Born–Huang elastic stiffness tensor
   at the atomic level, and predicts vibrational and mechanical properties
   better than BOO (Milkus & Zaccone 2016; Sci. Adv. 2022).

3. A perfect SiO4 tetrahedron (Td) has F_IS = −1/3, because Td has
   NO inversion centre.  More centrosymmetric distortions push F_IS
   toward +1.

4. TorchDisorder generates structures that satisfy BOTH experimental
   scattering data AND per-atom structural constraints (cn, tet, q4).
   Adding F_IS as a constraint or monitoring metric gives an additional
   handle on mechanical realism without any extra experimental input.

5. The MACE+torch_sim pipeline shows how to seamlessly combine
   TorchDisorder's differentiable scattering model with an accurate
   ML interatomic potential for downstream MD simulation and property
   prediction.

Next steps
----------
- Add 'fis' to the constraint JSON to directly penalise inversion asymmetry
  during TorchDisorder optimisation:
    order_parameters:
      fis: {{target: -0.25, min: -0.35, max: -0.15, weight: 1.0}}

- Run longer MACE MD and compute the vibrational density of states (VDOS)
  to see whether F_IS correlates with low-frequency modes (boson peak).

- Compare TorchDisorder-optimised vs. melt-quench structures from a
  longer MACE MD run using the perform_melt_quench helper:
    from torchdisorder.engine.optimizer import perform_melt_quench
    mq_state = perform_melt_quench(state, mace_model, T_high=4000, ...)
""")
